# Generated by Django 4.1.7 on 2023-05-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("monthly_pick", "monthly pick"),
                            ("most_popular", "most popular"),
                            ("latest_arrival", "latest arrival"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Product",
                "verbose_name_plural": "Home Products",
            },
        ),
    ]
