# Generated by Django 4.1.7 on 2023-05-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_homeproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomeProduct",
        ),
    ]
